name: CI/CD Mono repo Express + VueJs
on:
  push:
    branches: [*]
  pull_request:
  workflow_dispatch:

jobs:
  backend_ci:
    name: Backend CI (Express)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      # - name: Check lint
      #   run: npm run eslint:check

      # - name: Test
      #   run: npm run test

      - name: Build backend
        run: npm run build

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: back/dist

  backend_cd:
    name: Backend CD
    runs-on: ubuntu-latest
    need: backend_ci

    steps:
      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: back/dist

      - name: Deploy backend
        run: |
          echo "🚀 Deploying backend..."
          echo "✅ Backend deployed!"

  frontend_ci:
    name: Frontend CI (VUEJS)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint
        run: npm run lint

      - name: Build frontend
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: front/dist

  frontend-cd:
    name: Frontend CD (Deploy)
    runs-on: ubuntu-latest
    needs: frontend_ci

  steps:
    - name: Download frontend build artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: front/dist

    - name: Deploy frontend
      run: |
        echo "🚀 Deploying frontend..."
        # Exemple :
        # netlify deploy --dir=front/dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
        echo "✅ Frontend deployed!"
